name: Docker API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Push Api Docker Image to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: test/test
        registry: docker.io
        
        dockerfile: Dockerfile
        username: cheroberous
        password: cfda228b-1251-4545-b621-b4c4e40b03b4
        addLatest: true